# Generated by Django 5.2 on 2025-05-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresses',
            name='country',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adresses',
            name='district',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adresses',
            name='states',
            field=models.IntegerField(max_length=50),
        ),
    ]
