# Generated by Django 5.2 on 2025-05-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_adresses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='adress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.adresses'),
            preserve_default=False,
        ),
    ]
