# Generated by Django 5.2 on 2025-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_adresses_country_alter_adresses_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
